### ISSUE TITLE
Update to 1.18

### ISSUE THREAD

**Issue by he3als** [glossnyx/vibes#1]
Hello, I used to use this mod back in 1.16, but now 1.18 is the latest version and the mod no longer works. I have tried editing the `fabric.mod.json` to make it at least start with 1.18, but it crashes with an error. https://paste.ee/p/cnuCd

**Comment by auxves** [comment]
I've updated it for 1.18. You can find the jar [here](https://github.com/glossnyx/vibes/releases/tag/v2.0.1) :)

**Comment by he3als** [comment]
oh great tysm :)
