### ISSUE TITLE
Suggestion: Curio/Trinket compatibility

### ISSUE THREAD

**Issue by K-Proj** [glossnyx/vibes#5]
This mod is phenomenal. I've curated a bunch of music and added them into my own mod (unfortunately disco addons makes my client crash) just because this mod makes it really nice to listen to music in-game. 

The only thing I could see, that would make this mod any better, is the ability to hold the Vibe in a curio slot. I'm in Forge so I can't use Trinket, so I have a bias towards Curio. But I'm sure Fabric users would love Trinket compatibility. (I'm using Sinytra Connector & Forgified Fabric API to run this mod in Forge). 

Otherwise, I guess an inventory for the Vibe with the ability to change songs inside the Vibe somehow, is another idea, but this might not be worth the troubles of adding. 

Either way thanks for the mod!

**Comment by auxves** [comment]
Check out v3.1.0! Since this is a Fabric mod, I don't guarantee support for the Forge Connector, but I have tested it and it should work :)
